# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQQgl7hj0u7po0kt1xBQlez_PLWqwV48
"""

import numpy as np
from matplotlib import pyplot as plt

x=np.arange(1,11)
x

y=2*x
y

plt.plot(x,y)
plt.show()

#adding title and label
plt.plot(x,y)
plt.title("Line Plot")
plt.xlabel("X-Label")
plt.ylabel("Y-label")
plt.show()

#chalnge line aesthestics
plt.plot(x,y,color="black",linestyle=":",linewidth="3")
plt.title("Dot Plot")
plt.xlabel("X-Label")
plt.ylabel("Y-label")
plt.show()

x

y1=2*x
y2=3*x
y1
y2

#Adding three lines in same plot
plt.plot(x,y1,color="r",linestyle=":",linewidth="3")
plt.plot(x,y2,color="b",linestyle=":",linewidth="3")
plt.title("Two Line Plot")
plt.xlabel("X-Label")
plt.ylabel("Y-label")
plt.grid(True)
plt.show()

plt.subplot(2,1,1)
plt.plot(x,y1,color="r",linestyle=":",linewidth="3")
plt.title("Sub plot")
plt.xlabel("X-Label")
plt.ylabel("Y-label")



plt.subplot(2,1,2)
plt.plot(x,y2,color="b",linestyle=":",linewidth="3")
plt.title("Sub Plot")
plt.xlabel("X-Label")
plt.ylabel("Y-label")
plt.grid(True)
plt.show()

import numpy as np
student={"Bob":87,"Matt":56,"Anne":100,"Sam":27}
names=list(student.keys())
names

values=list(student.values())
values

plt.bar(names,values)
plt.show()

#Adding title and labels
plt.bar(names,values)
plt.title("Students Marks Distribution")
plt.xlabel("Students Name")
plt.ylabel("Students Marks")
plt.show()

#Horizontal Bar Graphs
plt.barh(names,values,color="g")
plt.title("Students Marks Distribution")
plt.xlabel("Students Name")
plt.ylabel("Students Marks")
plt.show()

#Scatter Graph
import numpy as np
x=[10,20,30,40,50,60]
y=[2,3,4,8,9,5,]
x

y

plt.scatter(x,y)
plt.show()

#Adding two plots 
x=[10,20,30,40,50,60,70,80,90]
a=[8,5,4,6,8,9,2,3,8]
b=[7,8,5,6,3,5,62,8,5]

plt.scatter(x,a,marker="*",c="g",s=100)
plt.scatter(x,b,marker=".",c="r",s=100)
plt.show()

#Sub SLot
plt.subplot(1,2,1)
plt.scatter(x,a,marker="*",c="g",s=100)


plt.subplot(1,2,2)
plt.scatter(x,b,marker=".",c="r",s=200)
plt.show()

#Histogram
import numpy as np
data=[5,5,6,6,7,7,3,7,8,8,]
plt.hist(data)
plt.show()

#Change colour
plt.hist(data,color="r")
plt.show()

#Pie Chart
fruits=['Mango','Orange','Apple','Gauva']
quantity=[34,65,100,29]
plt.pie(quantity,labels=fruits)
plt.show()

